name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install required dependencies
        run: |
          sudo apt-get update
          sudo apt-get -yqq install libwoff1 libopus0 libwebp6 libwebpdemux2 libenchant1c2a libgudev-1.0-0 libsecret-1-0 libhyphen0 libgdk-pixbuf2.0-0 libegl1 libnotify4 libxslt1.1 libevent-2.1-6 libgles2 libgl1 libvpx5 libnss3 libxss1 libasound2

      - name: Install node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install packages
        run: yarn install --lockfile

      - name: Lint
        run: yarn lint

      - name: Run test
        run: yarn test:ci

#      - name: Archive html report
#        uses: actions/upload-artifact@v1
#        with:
#          name: allure report
#          path: reports/report.html
