name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Start xvfb
        run: |
          sudo apt-get install xvfb
          export DISPLAY=':99.0'
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

      - name: Install node.js 12
        uses: actions/setup-node@v1
        with:
          version: 12

      - name: Run test
        run: |
          npm ci
          npm run test:ci

#      - name: Archive html report
#        uses: actions/upload-artifact@v1
#        with:
#          name: allure report
#          path: reports/report.html
